//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Storage
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Запись в накладной.
    /// </summary>
    // *** Start programmer edit section *** (ЗаписьВНакладной CustomAttributes)

    // *** End programmer edit section *** (ЗаписьВНакладной CustomAttributes)
    [AutoAltered()]
    [Caption("Запись в накладной")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаписьВНакладнойE", new string[] {
            "Сумма as \'Сумма\'",
            "Количество as \'Количество\'",
            "Цена as \'Цена\'",
            "Вес as \'Вес\'"})]
    public class ЗаписьВНакладной : ICSSoft.STORMNET.DataObject
    {
        
        private double fСумма;
        
        private int fКоличество;
        
        private double fЦена;
        
        private double fВес;
        
        private IIS.Storage.Накладная fНакладная;
        
        // *** Start programmer edit section *** (ЗаписьВНакладной CustomMembers)

        // *** End programmer edit section *** (ЗаписьВНакладной CustomMembers)

        
        /// <summary>
        /// Вес.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьВНакладной.Вес CustomAttributes)

        // *** End programmer edit section *** (ЗаписьВНакладной.Вес CustomAttributes)
        public virtual double Вес
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьВНакладной.Вес Get start)

                // *** End programmer edit section *** (ЗаписьВНакладной.Вес Get start)
                double result = this.fВес;
                // *** Start programmer edit section *** (ЗаписьВНакладной.Вес Get end)

                // *** End programmer edit section *** (ЗаписьВНакладной.Вес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьВНакладной.Вес Set start)

                // *** End programmer edit section *** (ЗаписьВНакладной.Вес Set start)
                this.fВес = value;
                // *** Start programmer edit section *** (ЗаписьВНакладной.Вес Set end)

                // *** End programmer edit section *** (ЗаписьВНакладной.Вес Set end)
            }
        }
        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьВНакладной.Количество CustomAttributes)

        // *** End programmer edit section *** (ЗаписьВНакладной.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьВНакладной.Количество Get start)

                // *** End programmer edit section *** (ЗаписьВНакладной.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (ЗаписьВНакладной.Количество Get end)

                // *** End programmer edit section *** (ЗаписьВНакладной.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьВНакладной.Количество Set start)

                // *** End programmer edit section *** (ЗаписьВНакладной.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (ЗаписьВНакладной.Количество Set end)

                // *** End programmer edit section *** (ЗаписьВНакладной.Количество Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьВНакладной.Сумма CustomAttributes)

        // *** End programmer edit section *** (ЗаписьВНакладной.Сумма CustomAttributes)
        public virtual double Сумма
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьВНакладной.Сумма Get start)

                // *** End programmer edit section *** (ЗаписьВНакладной.Сумма Get start)
                double result = this.fСумма;
                // *** Start programmer edit section *** (ЗаписьВНакладной.Сумма Get end)

                // *** End programmer edit section *** (ЗаписьВНакладной.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьВНакладной.Сумма Set start)

                // *** End programmer edit section *** (ЗаписьВНакладной.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (ЗаписьВНакладной.Сумма Set end)

                // *** End programmer edit section *** (ЗаписьВНакладной.Сумма Set end)
            }
        }
        
        /// <summary>
        /// Цена.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьВНакладной.Цена CustomAttributes)

        // *** End programmer edit section *** (ЗаписьВНакладной.Цена CustomAttributes)
        public virtual double Цена
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьВНакладной.Цена Get start)

                // *** End programmer edit section *** (ЗаписьВНакладной.Цена Get start)
                double result = this.fЦена;
                // *** Start programmer edit section *** (ЗаписьВНакладной.Цена Get end)

                // *** End programmer edit section *** (ЗаписьВНакладной.Цена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьВНакладной.Цена Set start)

                // *** End programmer edit section *** (ЗаписьВНакладной.Цена Set start)
                this.fЦена = value;
                // *** Start programmer edit section *** (ЗаписьВНакладной.Цена Set end)

                // *** End programmer edit section *** (ЗаписьВНакладной.Цена Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Storage.Накладная.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьВНакладной.Накладная CustomAttributes)

        // *** End programmer edit section *** (ЗаписьВНакладной.Накладная CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Накладная"})]
        public virtual IIS.Storage.Накладная Накладная
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьВНакладной.Накладная Get start)

                // *** End programmer edit section *** (ЗаписьВНакладной.Накладная Get start)
                IIS.Storage.Накладная result = this.fНакладная;
                // *** Start programmer edit section *** (ЗаписьВНакладной.Накладная Get end)

                // *** End programmer edit section *** (ЗаписьВНакладной.Накладная Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьВНакладной.Накладная Set start)

                // *** End programmer edit section *** (ЗаписьВНакладной.Накладная Set start)
                this.fНакладная = value;
                // *** Start programmer edit section *** (ЗаписьВНакладной.Накладная Set end)

                // *** End programmer edit section *** (ЗаписьВНакладной.Накладная Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаписьВНакладнойE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаписьВНакладнойE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаписьВНакладнойE", typeof(IIS.Storage.ЗаписьВНакладной));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ЗаписьВНакладной.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfЗаписьВНакладной CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfЗаписьВНакладной CustomAttributes)
    public class DetailArrayOfЗаписьВНакладной : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Storage.DetailArrayOfЗаписьВНакладной members)

        // *** End programmer edit section *** (IIS.Storage.DetailArrayOfЗаписьВНакладной members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ЗаписьВНакладной by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ЗаписьВНакладной.
        /// </summary>
        public DetailArrayOfЗаписьВНакладной(IIS.Storage.Накладная fНакладная) : 
                base(typeof(ЗаписьВНакладной), ((ICSSoft.STORMNET.DataObject)(fНакладная)))
        {
        }
        
        public IIS.Storage.ЗаписьВНакладной this[int index]
        {
            get
            {
                return ((IIS.Storage.ЗаписьВНакладной)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Storage.ЗаписьВНакладной dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
