//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Storage
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заказ.
    /// </summary>
    // *** Start programmer edit section *** (Заказ CustomAttributes)

    // *** End programmer edit section *** (Заказ CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаказE", new string[] {
            "ДатаОплаты as \'Дата оплаты\'",
            "Цена as \'Цена\'",
            "ДатаОтгрузки as \'Дата отгрузки\'",
            "Статус as \'Статус\'"})]
    [AssociatedDetailViewAttribute("ЗаказE", "СтрокаЗаказа", "СтрокаЗаказаE", true, "", "Строка заказа", true, new string[] {
            ""})]
    [View("ЗаказL", new string[] {
            "ДатаОплаты as \'Дата оплаты\'",
            "Цена as \'Цена\'",
            "ДатаОтгрузки as \'Дата отгрузки\'",
            "Статус as \'Статус\'"})]
    public class Заказ : IIS.Storage.Документ
    {
        
        private System.DateTime fДатаОплаты;
        
        private double fЦена;
        
        private System.DateTime fДатаОтгрузки;
        
        private IIS.Storage.СостояниеЗаказа fСтатус;
        
        private IIS.Storage.Сотрудник fСотрудник;
        
        private IIS.Storage.DetailArrayOfСтрокаЗаказа fСтрокаЗаказа;
        
        // *** Start programmer edit section *** (Заказ CustomMembers)

        // *** End programmer edit section *** (Заказ CustomMembers)

        
        /// <summary>
        /// ДатаОплаты.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.ДатаОплаты CustomAttributes)

        // *** End programmer edit section *** (Заказ.ДатаОплаты CustomAttributes)
        public virtual System.DateTime ДатаОплаты
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.ДатаОплаты Get start)

                // *** End programmer edit section *** (Заказ.ДатаОплаты Get start)
                System.DateTime result = this.fДатаОплаты;
                // *** Start programmer edit section *** (Заказ.ДатаОплаты Get end)

                // *** End programmer edit section *** (Заказ.ДатаОплаты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.ДатаОплаты Set start)

                // *** End programmer edit section *** (Заказ.ДатаОплаты Set start)
                this.fДатаОплаты = value;
                // *** Start programmer edit section *** (Заказ.ДатаОплаты Set end)

                // *** End programmer edit section *** (Заказ.ДатаОплаты Set end)
            }
        }
        
        /// <summary>
        /// ДатаОтгрузки.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.ДатаОтгрузки CustomAttributes)

        // *** End programmer edit section *** (Заказ.ДатаОтгрузки CustomAttributes)
        public virtual System.DateTime ДатаОтгрузки
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.ДатаОтгрузки Get start)

                // *** End programmer edit section *** (Заказ.ДатаОтгрузки Get start)
                System.DateTime result = this.fДатаОтгрузки;
                // *** Start programmer edit section *** (Заказ.ДатаОтгрузки Get end)

                // *** End programmer edit section *** (Заказ.ДатаОтгрузки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.ДатаОтгрузки Set start)

                // *** End programmer edit section *** (Заказ.ДатаОтгрузки Set start)
                this.fДатаОтгрузки = value;
                // *** Start programmer edit section *** (Заказ.ДатаОтгрузки Set end)

                // *** End programmer edit section *** (Заказ.ДатаОтгрузки Set end)
            }
        }
        
        /// <summary>
        /// Статус.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Статус CustomAttributes)

        // *** End programmer edit section *** (Заказ.Статус CustomAttributes)
        public virtual IIS.Storage.СостояниеЗаказа Статус
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Статус Get start)

                // *** End programmer edit section *** (Заказ.Статус Get start)
                IIS.Storage.СостояниеЗаказа result = this.fСтатус;
                // *** Start programmer edit section *** (Заказ.Статус Get end)

                // *** End programmer edit section *** (Заказ.Статус Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Статус Set start)

                // *** End programmer edit section *** (Заказ.Статус Set start)
                this.fСтатус = value;
                // *** Start programmer edit section *** (Заказ.Статус Set end)

                // *** End programmer edit section *** (Заказ.Статус Set end)
            }
        }
        
        /// <summary>
        /// Цена.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Цена CustomAttributes)

        // *** End programmer edit section *** (Заказ.Цена CustomAttributes)
        public virtual double Цена
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Цена Get start)

                // *** End programmer edit section *** (Заказ.Цена Get start)
                double result = this.fЦена;
                // *** Start programmer edit section *** (Заказ.Цена Get end)

                // *** End programmer edit section *** (Заказ.Цена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Цена Set start)

                // *** End programmer edit section *** (Заказ.Цена Set start)
                this.fЦена = value;
                // *** Start programmer edit section *** (Заказ.Цена Set end)

                // *** End programmer edit section *** (Заказ.Цена Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (Заказ.Сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудник"})]
        [NotNull()]
        public virtual IIS.Storage.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Сотрудник Get start)

                // *** End programmer edit section *** (Заказ.Сотрудник Get start)
                IIS.Storage.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (Заказ.Сотрудник Get end)

                // *** End programmer edit section *** (Заказ.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Сотрудник Set start)

                // *** End programmer edit section *** (Заказ.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (Заказ.Сотрудник Set end)

                // *** End programmer edit section *** (Заказ.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.СтрокаЗаказа CustomAttributes)

        // *** End programmer edit section *** (Заказ.СтрокаЗаказа CustomAttributes)
        public virtual IIS.Storage.DetailArrayOfСтрокаЗаказа СтрокаЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.СтрокаЗаказа Get start)

                // *** End programmer edit section *** (Заказ.СтрокаЗаказа Get start)
                if ((this.fСтрокаЗаказа == null))
                {
                    this.fСтрокаЗаказа = new IIS.Storage.DetailArrayOfСтрокаЗаказа(this);
                }
                IIS.Storage.DetailArrayOfСтрокаЗаказа result = this.fСтрокаЗаказа;
                // *** Start programmer edit section *** (Заказ.СтрокаЗаказа Get end)

                // *** End programmer edit section *** (Заказ.СтрокаЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.СтрокаЗаказа Set start)

                // *** End programmer edit section *** (Заказ.СтрокаЗаказа Set start)
                this.fСтрокаЗаказа = value;
                // *** Start programmer edit section *** (Заказ.СтрокаЗаказа Set end)

                // *** End programmer edit section *** (Заказ.СтрокаЗаказа Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаказE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказE", typeof(IIS.Storage.Заказ));
                }
            }
            
            /// <summary>
            /// "ЗаказL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказL", typeof(IIS.Storage.Заказ));
                }
            }
        }
    }
}
