//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Storage
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Склад.
    /// </summary>
    // *** Start programmer edit section *** (Склад CustomAttributes)

    // *** End programmer edit section *** (Склад CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СкладE", new string[] {
            "Номер as \'Номер\'",
            "Адрес as \'Адрес\'"})]
    [AssociatedDetailViewAttribute("СкладE", "ТоварНаСкладе", "ТоварНаСкладеE", true, "", "Товар на складе", true, new string[] {
            ""})]
    [View("СкладL", new string[] {
            "Номер as \'Номер\'",
            "Адрес as \'Адрес\'"})]
    public class Склад : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private string fАдрес;
        
        private IIS.Storage.Сотрудник fСотрудник;
        
        private IIS.Storage.DetailArrayOfТоварНаСкладе fТоварНаСкладе;
        
        // *** Start programmer edit section *** (Склад CustomMembers)

        // *** End programmer edit section *** (Склад CustomMembers)

        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (Склад.Адрес CustomAttributes)

        // *** End programmer edit section *** (Склад.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (Склад.Адрес Get start)

                // *** End programmer edit section *** (Склад.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (Склад.Адрес Get end)

                // *** End programmer edit section *** (Склад.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Склад.Адрес Set start)

                // *** End programmer edit section *** (Склад.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (Склад.Адрес Set end)

                // *** End programmer edit section *** (Склад.Адрес Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Склад.Номер CustomAttributes)

        // *** End programmer edit section *** (Склад.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Склад.Номер Get start)

                // *** End programmer edit section *** (Склад.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Склад.Номер Get end)

                // *** End programmer edit section *** (Склад.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Склад.Номер Set start)

                // *** End programmer edit section *** (Склад.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Склад.Номер Set end)

                // *** End programmer edit section *** (Склад.Номер Set end)
            }
        }
        
        /// <summary>
        /// Склад.
        /// </summary>
        // *** Start programmer edit section *** (Склад.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (Склад.Сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудник"})]
        [NotNull()]
        public virtual IIS.Storage.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (Склад.Сотрудник Get start)

                // *** End programmer edit section *** (Склад.Сотрудник Get start)
                IIS.Storage.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (Склад.Сотрудник Get end)

                // *** End programmer edit section *** (Склад.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Склад.Сотрудник Set start)

                // *** End programmer edit section *** (Склад.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (Склад.Сотрудник Set end)

                // *** End programmer edit section *** (Склад.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// Склад.
        /// </summary>
        // *** Start programmer edit section *** (Склад.ТоварНаСкладе CustomAttributes)

        // *** End programmer edit section *** (Склад.ТоварНаСкладе CustomAttributes)
        public virtual IIS.Storage.DetailArrayOfТоварНаСкладе ТоварНаСкладе
        {
            get
            {
                // *** Start programmer edit section *** (Склад.ТоварНаСкладе Get start)

                // *** End programmer edit section *** (Склад.ТоварНаСкладе Get start)
                if ((this.fТоварНаСкладе == null))
                {
                    this.fТоварНаСкладе = new IIS.Storage.DetailArrayOfТоварНаСкладе(this);
                }
                IIS.Storage.DetailArrayOfТоварНаСкладе result = this.fТоварНаСкладе;
                // *** Start programmer edit section *** (Склад.ТоварНаСкладе Get end)

                // *** End programmer edit section *** (Склад.ТоварНаСкладе Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Склад.ТоварНаСкладе Set start)

                // *** End programmer edit section *** (Склад.ТоварНаСкладе Set start)
                this.fТоварНаСкладе = value;
                // *** Start programmer edit section *** (Склад.ТоварНаСкладе Set end)

                // *** End programmer edit section *** (Склад.ТоварНаСкладе Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СкладE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СкладE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СкладE", typeof(IIS.Storage.Склад));
                }
            }
            
            /// <summary>
            /// "СкладL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СкладL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СкладL", typeof(IIS.Storage.Склад));
                }
            }
        }
    }
}
