//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Storage
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состояние накладной.
    /// </summary>
    // *** Start programmer edit section *** (СостояниеНакладной CustomAttributes)

    // *** End programmer edit section *** (СостояниеНакладной CustomAttributes)
    public enum СостояниеНакладной
    {
        
        // *** Start programmer edit section *** (СостояниеНакладной.Отгруженная CustomAttributes)

        // *** End programmer edit section *** (СостояниеНакладной.Отгруженная CustomAttributes)
        Отгруженная,
        
        // *** Start programmer edit section *** (СостояниеНакладной.Готовая CustomAttributes)

        // *** End programmer edit section *** (СостояниеНакладной.Готовая CustomAttributes)
        Готовая,
        
        // *** Start programmer edit section *** (СостояниеНакладной.Новый CustomAttributes)

        // *** End programmer edit section *** (СостояниеНакладной.Новый CustomAttributes)
        Новый,
        
        // *** Start programmer edit section *** (СостояниеНакладной.Выписанная CustomAttributes)

        // *** End programmer edit section *** (СостояниеНакладной.Выписанная CustomAttributes)
        Выписанная,
        
        // *** Start programmer edit section *** (СостояниеНакладной.Приостановленная CustomAttributes)

        // *** End programmer edit section *** (СостояниеНакладной.Приостановленная CustomAttributes)
        Приостановленная,
    }
}
